Feature/security
icat-food/ms-onboarding pull request #7
Opened 2022-07-14 02:35 UTC by Vandeilsonln

# O que foi feito
- Implementado fluxo de autenticação e autorização com JWT baseado em Roles
- Criado Factory genérica de Domain e DTOs para simplificação da escrita dos testes

# Observações / Dúvidas
- O ```@Lazy``` foi utilizado na classe ```AuthenticationService``` para evitar uma dependência cíclica entre ele e a classe ```SecurityConfiguration```, que extende de ```WebSecurityConfigurerAdapter```, que por sua vez também usa um ```AuthenticationManager```, assim como a service de autenticação.

- Nos testes de autenticação, usei a anotação ```@WithUserDetails```, que é pra fazer uma autenticação com base no e-mail do usuário que é passado como argumento. Os testes passam pois os users já existem no banco graças aos inserts do ```afterMigrate.sql``` que o Flyway roda na hora de subir a aplicação. Entendo que esse callback não vai ser usado quando a gente rodar a aplicação na nuvem, ficando só pra desenvolvimento mesmo, e o ideal talvez seria salvar os users no ```@BeforeEach```, mas como precisa instanciar e salvar um User e em seguida um Restaurant/Consumer/Delivery, eu acabaria tendo que injetar a classe de persistência dessas duas entidades. Você vê algum problema em fazer um ```@Autowired``` nelas pra isso?
- E também queria saber se você conhece alguma outra forma de popular o banco de dados pros testes sem ser pelo BeforeEach. Sei lá, de repente fazer o afterMigrate.sql rodar no github actions na hora dos testes. Não sei a complexidade disso, é mais pra curiosidade mesmo.

2022-07-16 23:35 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/configuration/TokenAuthFilterConfiguration.kt
> +    private val tokenService: TokenService,
Opa maninho, para mantermos o padrão de acesso ao application do projeto, aqui podemos utilizar a interface port `TokenServicePort` para acessar a service do token

2022-07-16 23:36 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/configuration/TokenAuthFilterConfiguration.kt
> +        val tokenFromHeader: String? = getTokenFromHeader(request)
```suggestion
        val tokenFromHeader = getTokenFromHeader(request)
```
Como o método `getTokenFromHeader` retorna uma String, aqui você pode passar diretamente ser deixar a tipagem explicita

2022-07-16 23:39 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/configuration/TokenAuthFilterConfiguration.kt
> +        val email: String? = tokenService.getTokenId(tokenFromHeader)
```suggestion
        val email = tokenService.getTokenId(tokenFromHeader)
```

2022-07-16 23:40 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/configuration/TokenAuthFilterConfiguration.kt
> +            val user: UserEntity = optionalUser.get()
```suggestion
        val email = tokenService.getTokenId(tokenFromHeader)
        val optionalUser = repository.findByEmailIgnoreCase(email!!)
        if (optionalUser.isPresent) {
            val user = optionalUser.get()
```

2022-07-16 23:45 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/inbound/controllers/AuthenticationController.kt
> +    @Autowired val authenticationServicePort: AuthenticationServicePort
```suggestion
    val authenticationServicePort: AuthenticationServicePort
```
Maninho, nas classes que estiverem anotadas com os stereotypes do Spring, não precisa passar o @Autowired

2022-07-16 23:47 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/inbound/controllers/AuthenticationController.kt
> +    @Autowired val authenticationServicePort: AuthenticationServicePort
```suggestion
    private val authenticationServicePort: AuthenticationServicePort
```
Nas injeções de dependencia seria bom colocar como privadas tbm, fazendo com que fique explicito que aquela injeção, pertence somente a classe que esta injetando ela.

2022-07-16 23:50 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/outbound/persistence/mysql/UserPersistence.kt
> +    override fun getUserByEmail(email: String): UserEntity =
```suggestion
    override fun getUserByEmail(email: String): UserDomain =
```
Opa Maninho, o correto aqui é sempre externalizarmos as classes do contexto de adapter para a camada de application, pois se não, acabamos ferindo o contexto da camada de application conhecer somente as classes que são de application.

2022-07-16 23:51 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/outbound/persistence/mysql/UserPersistence.kt
> +    override fun getUserByEmail(email: String): UserEntity =
```suggestion
    override fun getUserByEmail(email: String): UserDomain =
```
Opa Maninho, o correto aqui é sempre externalizarmos as classes do contexto de adapter para a camada de application, pois se não, acabamos ferindo o contexto da camada de application conhecer somente as classes que são de application.

2022-07-16 23:57 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/outbound/persistence/mysql/entities/RoleEntity.kt
> +    private val id: Int? = null,
```suggestion
    @Id
    @Column(unique = true, nullable = false, length = 50)
    val id: String? = null,
```
Maninho, como todos as nossas outras entidades os identificadores são uuids, o que acha da gente deixar aqui tbm, para mantermos o padrão?

2022-07-17 00:00 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/application/ports/inbound/AuthenticationServicePort.kt
> +    fun authenticate(loginDTO: LoginDTO): TokenDTO
```suggestion
    fun authenticate(loginDTO: LoginDTO): TokenDomain
```
Opa maninho, seguindo as regrinhas da arquitetura, aqui teria que retornar um TokenDomain, por exemplo, pois se não o application acaba tendo código da camada de adapters

2022-07-17 00:00 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/application/services/AuthenticationService.kt
> +
```suggestion
```

2022-07-17 00:22 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/application/services/TokenService.kt
> +class TokenService: TokenServicePort {
Maninho, essa classe infringe bastante a arquitetura, mas eu não consegui pensar em nada a gente pudesse fazer, então acho que como é uma coisa muito especifica e não contém regras de negócio, a gente pode mandar bala assim mesmo

2022-07-17 00:22 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/application/services/TokenService.kt
> +class TokenService: TokenServicePort {
Maninho, essa classe infringe bastante a arquitetura, mas eu não consegui pensar em nada a gente pudesse fazer, então acho que como é uma coisa muito especifica e não contém regras de negócio, a gente pode mandar bala assim mesmo

2022-07-17 00:23 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/application/services/UserService.kt
> +        val encryptedPassword: String = passwordEncryptor.encode(userDomain.password)
```suggestion
        val encryptedPassword = passwordEncryptor.encode(userDomain.password)
```

2022-07-17 00:28 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/application/services/UserService.kt
> +        val encryptedPassword: String = passwordEncryptor.encode(userDomain.password)
```suggestion
        val encryptedPassword = passwordEncryptor.encode(userDomain.password)
```

2022-07-17 00:33 UTC, kaikeventura commented on target/classes/db/migration/V1__create_user_table.sql
> +);
```suggestion
```
Maninho, essa migration vai acabar conflitando com a migration V1 que esta na main

2022-07-17 00:36 UTC, kaikeventura requested changes
Maninho, respondendo as perguntinhas:
* No conexto de testes não tem problema utilziar o @Autowired, pode mandar bala
* Sobre rodarem alguns sqls antes de rodar os testes tem como sim maninho, é parecido com o que tem no SE do PP, qualquer coisa, podemos deixar dessa maneira por enquanto, ai criamos um card no trello para fazermos essa melhoria depois.

2022-07-19 01:22 UTC, Vandeilsonln commented on src/main/kotlin/com/icat/orboarding/user/adapters/configuration/TokenAuthFilterConfiguration.kt
> +            val user: UserEntity = optionalUser.get()
Feito, maninhoo/.
Depois de um tempo mexendo no Java, chega dá um tchãn no coração ao não tipar alguma variável kkkkk

2022-07-19 01:48 UTC, Vandeilsonln commented on src/main/kotlin/com/icat/orboarding/user/adapters/outbound/persistence/mysql/UserPersistence.kt
> +    override fun getUserByEmail(email: String): UserEntity =
Boa, saquei!!!

Lá no AuthenticationService, no método ```loadUserByUsername```, é necessário uma classe que implemente a interface ```UserDetails```, que eu acabei deixando na UserEntity com base nos exemplos que vi. Não tinha me atentado a essa questão da quebra da arquitetura mesmo.

Pensei em criar uma outra classe, UserSecurity, que implementaria ela e faria esse método da persistence retornar ela usando aquelas funções de extensão, tipo um `UserEntity.toUserSecurity()`. Ou então fazer a `UserDomain` implementar essa `UserDetails`, mas n me parece certo deixar essa questão de sec numa classe dentro de application.

2022-07-19 01:49 UTC, Vandeilsonln commented on src/main/kotlin/com/icat/orboarding/user/adapters/outbound/persistence/mysql/entities/RoleEntity.kt
> +    private val id: Int? = null,
Fechou manin, pode ser, alterado o/

2022-07-19 02:09 UTC, Vandeilsonln commented on src/main/kotlin/com/icat/orboarding/user/application/services/TokenService.kt
> +class TokenService: TokenServicePort {
Acho que saquei, a gente tem referência de Entity e tbm depende de libs externas, como o spring security e jsonwebtoken.  N sei se tem vantagem em tirar ele de application e colocar em alguma classe como um TokenConfig nos adapters, mas talvez ataque menos a arquitetura do que deixar ela no application.

2022-07-19 02:20 UTC, Vandeilsonln commented on target/classes/db/migration/V1__create_user_table.sql
> +);
Opa meu mano, eu fiquei encucado com isso porque nem cheguei a mexer na V1, só na V6 e V7. Mas eu vi que essa classe que o github acusou foi do diretório `target/classes/db/migration/`. Estranho, n sei pq ignorou o .gitignore, mas ela n vai subir pra main não, ainda bem que você notou hehe

2022-08-03 00:26 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/outbound/persistence/mysql/UserPersistence.kt
> +    override fun getUserByEmail(email: String): UserEntity =
Vamos deixar assim por enquanto maninho, mas vou criar uma terefinha de débito técnico pra gente tentar encontrar uma forma de contornar isso, o que acha?

2022-08-03 00:27 UTC, kaikeventura commented on src/main/kotlin/com/icat/orboarding/user/adapters/inbound/dtos/response/TokenDTO.kt
> +}
```suggestion
}
```
```suggestion
data class TokenDTO(var token: String)
```

2022-08-03 00:29 UTC, kaikeventura approved these changes
TOP demais maninho, arrasou :pepelove:

2022-08-04 02:26 UTC, merged